// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter } from "nanopack";

import { Widget } from "../widget/widget.np.js";
import { FontStyle } from "../style/font-style.np.js";
import { ViewStyle } from "../style/view-style.np.js";

class Text extends Widget {
  public static TYPE_ID = 3495336243;

  public override readonly typeId: number = 3495336243;

  public override readonly headerSize: number = 24;

  constructor(
    public style: ViewStyle,
    public tag: number | null,
    public content: string,
    public font: FontStyle,
    public tw: string,
  ) {
    super(style, tag);
  }

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Text } | null {
    const reader = new NanoBufReader(bytes);
    return Text.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: Text } | null {
    let ptr = 24;

    const maybeStyle = ViewStyle.fromReader(reader.newReaderAt(ptr));
    if (!maybeStyle) {
      return null;
    }
    const style = maybeStyle.result;
    ptr += maybeStyle.bytesRead;

    let tag: number | null;
    if (reader.readFieldSize(1) >= 0) {
      tag = reader.readInt32(ptr);
      ptr += 4;
    } else {
      tag = null;
    }

    const contentByteLength = reader.readFieldSize(2);
    const content = reader.readString(ptr, contentByteLength);
    ptr += contentByteLength;

    const maybeFont = FontStyle.fromReader(reader.newReaderAt(ptr));
    if (!maybeFont) {
      return null;
    }
    const font = maybeFont.result;
    ptr += maybeFont.bytesRead;

    const twByteLength = reader.readFieldSize(4);
    const tw = reader.readString(ptr, twByteLength);
    ptr += twByteLength;

    return { bytesRead: ptr, result: new Text(style, tag, content, font, tw) };
  }

  public override writeTo(writer: NanoBufWriter, offset: number = 0): number {
    let bytesWritten = 24;

    writer.writeTypeId(3495336243, offset);

    const styleData = this.style.bytes();
    writer.appendBytes(styleData);
    writer.writeFieldSize(0, styleData.byteLength, offset);
    bytesWritten += styleData.byteLength;

    if (this.tag) {
      writer.appendInt32(this.tag);
      writer.writeFieldSize(1, 4, offset);
      bytesWritten += 4;
    } else {
      writer.writeFieldSize(1, -1, offset);
    }

    const contentByteLength = writer.appendString(this.content);
    writer.writeFieldSize(2, contentByteLength, offset);
    bytesWritten += contentByteLength;

    const fontData = this.font.bytes();
    writer.appendBytes(fontData);
    writer.writeFieldSize(3, fontData.byteLength, offset);
    bytesWritten += fontData.byteLength;

    const twByteLength = writer.appendString(this.tw);
    writer.writeFieldSize(4, twByteLength, offset);
    bytesWritten += twByteLength;

    return bytesWritten;
  }

  public override bytes(): Uint8Array {
    const writer = new NanoBufWriter(24);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { Text };
