// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter } from "nanopack";

import { Widget } from "../widget/widget.np.js";
import { ViewStyle } from "../style/view-style.np.js";

class Center extends Widget {
  public static TYPE_ID = 1855640887;

  public override readonly typeId: number = 1855640887;

  public override readonly headerSize: number = 16;

  constructor(
    public style: ViewStyle,
    public tag: number | null,
    public child: Widget,
  ) {
    super(style, tag);
  }

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Center } | null {
    const reader = new NanoBufReader(bytes);
    return Center.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: Center } | null {
    let ptr = 16;

    const maybeStyle = ViewStyle.fromReader(reader.newReaderAt(ptr));
    if (!maybeStyle) {
      return null;
    }
    const style = maybeStyle.result;
    ptr += maybeStyle.bytesRead;

    let tag: number | null;
    if (reader.readFieldSize(1) >= 0) {
      tag = reader.readInt32(ptr);
      ptr += 4;
    } else {
      tag = null;
    }

    const maybeChild = Widget.fromReader(reader.newReaderAt(ptr));
    if (!maybeChild) {
      return null;
    }
    const child = maybeChild.result;
    ptr += maybeChild.bytesRead;

    return { bytesRead: ptr, result: new Center(style, tag, child) };
  }

  public override writeTo(writer: NanoBufWriter, offset: number = 0): number {
    let bytesWritten = 16;

    writer.writeTypeId(1855640887, offset);

    const styleData = this.style.bytes();
    writer.appendBytes(styleData);
    writer.writeFieldSize(0, styleData.byteLength, offset);
    bytesWritten += styleData.byteLength;

    if (this.tag) {
      writer.appendInt32(this.tag);
      writer.writeFieldSize(1, 4, offset);
      bytesWritten += 4;
    } else {
      writer.writeFieldSize(1, -1, offset);
    }

    const childData = this.child.bytes();
    writer.appendBytes(childData);
    writer.writeFieldSize(2, childData.byteLength, offset);
    bytesWritten += childData.byteLength;

    return bytesWritten;
  }

  public override bytes(): Uint8Array {
    const writer = new NanoBufWriter(16);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { Center };
