// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter, type NanoPackMessage } from "nanopack";

import { ViewStyle } from "../style/view-style.np.js";

class Widget implements NanoPackMessage {
  public static TYPE_ID = 1676374721;

  public readonly typeId: number = 1676374721;

  public readonly headerSize: number = 12;

  constructor(
    public style: ViewStyle,
    public tag: number | null,
  ) {}

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Widget } | null {
    const reader = new NanoBufReader(bytes);
    return Widget.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: Widget } | null {
    let ptr = 12;

    const maybeStyle = ViewStyle.fromReader(reader.newReaderAt(ptr));
    if (!maybeStyle) {
      return null;
    }
    const style = maybeStyle.result;
    ptr += maybeStyle.bytesRead;

    let tag: number | null;
    if (reader.readFieldSize(1) >= 0) {
      tag = reader.readInt32(ptr);
      ptr += 4;
    } else {
      tag = null;
    }

    return { bytesRead: ptr, result: new Widget(style, tag) };
  }

  public writeTo(writer: NanoBufWriter, offset: number = 0): number {
    let bytesWritten = 12;

    writer.writeTypeId(1676374721, offset);

    const styleData = this.style.bytes();
    writer.appendBytes(styleData);
    writer.writeFieldSize(0, styleData.byteLength, offset);
    bytesWritten += styleData.byteLength;

    if (this.tag) {
      writer.appendInt32(this.tag);
      writer.writeFieldSize(1, 4, offset);
      bytesWritten += 4;
    } else {
      writer.writeFieldSize(1, -1, offset);
    }

    return bytesWritten;
  }

  public bytes(): Uint8Array {
    const writer = new NanoBufWriter(12);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { Widget };
