// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter } from "nanopack";

import type { TAlignment } from "../alignment/alignment.np.js";
import { ViewStyle } from "../style/view-style.np.js";
import { Widget } from "../widget/widget.np.js";

class Row extends Widget {
  public static TYPE_ID = 1006836449;

  public override readonly typeId: number = 1006836449;

  public override readonly headerSize: number = 32;

  constructor(
    public style: ViewStyle,
    public tag: number | null,
    public width: number,
    public height: number,
    public horizontalAlignment: TAlignment,
    public verticalAlignment: TAlignment,
    public children: Widget[],
  ) {
    super(style, tag);
  }

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Row } | null {
    const reader = new NanoBufReader(bytes);
    return Row.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: Row } | null {
    let ptr = 32;

    const maybeStyle = ViewStyle.fromReader(reader.newReaderAt(ptr));
    if (!maybeStyle) {
      return null;
    }
    const style = maybeStyle.result;
    ptr += maybeStyle.bytesRead;

    let tag: number | null;
    if (reader.readFieldSize(1) >= 0) {
      tag = reader.readInt32(ptr);
      ptr += 4;
    } else {
      tag = null;
    }

    const width = reader.readDouble(ptr);
    ptr += 8;

    const height = reader.readDouble(ptr);
    ptr += 8;

    const horizontalAlignment = reader.readInt8(ptr) as TAlignment;
    ptr += 1;

    const verticalAlignment = reader.readInt8(ptr) as TAlignment;
    ptr += 1;

    const childrenLength = reader.readInt32(ptr);
    ptr += 4;
    const children: Widget[] = new Array(childrenLength);
    for (let i = 0; i < childrenLength; i++) {
      const maybeIItem = Widget.fromReader(reader.newReaderAt(ptr));
      if (!maybeIItem) {
        return null;
      }
      const iItem = maybeIItem.result;
      ptr += maybeIItem.bytesRead;
      children[i] = iItem;
    }

    return {
      bytesRead: ptr,
      result: new Row(
        style,
        tag,
        width,
        height,
        horizontalAlignment,
        verticalAlignment,
        children,
      ),
    };
  }

  public override writeTo(writer: NanoBufWriter, offset: number = 0): number {
    let bytesWritten = 32;

    writer.writeTypeId(1006836449, offset);

    const styleData = this.style.bytes();
    writer.appendBytes(styleData);
    writer.writeFieldSize(0, styleData.byteLength, offset);
    bytesWritten += styleData.byteLength;

    if (this.tag) {
      writer.appendInt32(this.tag);
      writer.writeFieldSize(1, 4, offset);
      bytesWritten += 4;
    } else {
      writer.writeFieldSize(1, -1, offset);
    }

    writer.appendDouble(this.width);
    writer.writeFieldSize(2, 8, offset);
    bytesWritten += 8;

    writer.appendDouble(this.height);
    writer.writeFieldSize(3, 8, offset);
    bytesWritten += 8;

    writer.appendInt8(this.horizontalAlignment);
    writer.writeFieldSize(4, 1, offset);
    bytesWritten += 1;

    writer.appendInt8(this.verticalAlignment);
    writer.writeFieldSize(5, 1, offset);
    bytesWritten += 1;

    writer.appendInt32(this.children.length);
    let childrenByteLength = 4;
    for (const iItem of this.children) {
      const iItemData = iItem.bytes();
      writer.appendBytes(iItemData);
      childrenByteLength += iItemData.byteLength;
    }
    writer.writeFieldSize(6, childrenByteLength, offset);
    bytesWritten += childrenByteLength;

    return bytesWritten;
  }

  public override bytes(): Uint8Array {
    const writer = new NanoBufWriter(32);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { Row };
