// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter } from "nanopack";

import { Widget } from "../widget/widget.np.js";
import { ViewStyle } from "../style/view-style.np.js";

class TextField extends Widget {
  public static TYPE_ID = 841129444;

  public override readonly typeId: number = 841129444;

  public override readonly headerSize: number = 24;

  constructor(
    public style: ViewStyle,
    public tag: number | null,
    public placeholder: string | null,
    public value: string,
    public onValueChanged: number,
  ) {
    super(style, tag);
  }

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: TextField } | null {
    const reader = new NanoBufReader(bytes);
    return TextField.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: TextField } | null {
    let ptr = 24;

    const maybeStyle = ViewStyle.fromReader(reader.newReaderAt(ptr));
    if (!maybeStyle) {
      return null;
    }
    const style = maybeStyle.result;
    ptr += maybeStyle.bytesRead;

    let tag: number | null;
    if (reader.readFieldSize(1) >= 0) {
      tag = reader.readInt32(ptr);
      ptr += 4;
    } else {
      tag = null;
    }

    let placeholder: string | null;
    if (reader.readFieldSize(2) >= 0) {
      const placeholderByteLength = reader.readFieldSize(2);
      placeholder = reader.readString(ptr, placeholderByteLength);
      ptr += placeholderByteLength;
    } else {
      placeholder = null;
    }

    const valueByteLength = reader.readFieldSize(3);
    const value = reader.readString(ptr, valueByteLength);
    ptr += valueByteLength;

    const onValueChanged = reader.readInt32(ptr);
    ptr += 4;

    return {
      bytesRead: ptr,
      result: new TextField(style, tag, placeholder, value, onValueChanged),
    };
  }

  public override writeTo(writer: NanoBufWriter, offset: number = 0): number {
    let bytesWritten = 24;

    writer.writeTypeId(841129444, offset);

    const styleData = this.style.bytes();
    writer.appendBytes(styleData);
    writer.writeFieldSize(0, styleData.byteLength, offset);
    bytesWritten += styleData.byteLength;

    if (this.tag) {
      writer.appendInt32(this.tag);
      writer.writeFieldSize(1, 4, offset);
      bytesWritten += 4;
    } else {
      writer.writeFieldSize(1, -1, offset);
    }

    if (this.placeholder) {
      const placeholderByteLength = writer.appendString(this.placeholder);
      writer.writeFieldSize(2, placeholderByteLength, offset);
      bytesWritten += placeholderByteLength;
    } else {
      writer.writeFieldSize(2, -1, offset);
    }

    const valueByteLength = writer.appendString(this.value);
    writer.writeFieldSize(3, valueByteLength, offset);
    bytesWritten += valueByteLength;

    writer.appendInt32(this.onValueChanged);
    writer.writeFieldSize(4, 4, offset);
    bytesWritten += 4;

    return bytesWritten;
  }

  public override bytes(): Uint8Array {
    const writer = new NanoBufWriter(24);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { TextField };
