// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufReader, NanoBufWriter } from "nanopack";

import { ViewStyle } from "../style/view-style.np.js";
import { Widget } from "../widget/widget.np.js";

class Button extends Widget {
  public static TYPE_ID = 320412644;

  public override readonly typeId: number = 320412644;

  public override readonly headerSize: number = 20;

  constructor(
    public style: ViewStyle,
    public tag: number | null,
    public text: string,
    public onClick: number,
  ) {
    super(style, tag);
  }

  public static fromBytes(
    bytes: Uint8Array,
  ): { bytesRead: number; result: Button } | null {
    const reader = new NanoBufReader(bytes);
    return Button.fromReader(reader);
  }

  public static fromReader(
    reader: NanoBufReader,
  ): { bytesRead: number; result: Button } | null {
    let ptr = 20;

    const maybeStyle = ViewStyle.fromReader(reader.newReaderAt(ptr));
    if (!maybeStyle) {
      return null;
    }
    const style = maybeStyle.result;
    ptr += maybeStyle.bytesRead;

    let tag: number | null;
    if (reader.readFieldSize(1) >= 0) {
      tag = reader.readInt32(ptr);
      ptr += 4;
    } else {
      tag = null;
    }

    const textByteLength = reader.readFieldSize(2);
    const text = reader.readString(ptr, textByteLength);
    ptr += textByteLength;

    const onClick = reader.readInt32(ptr);
    ptr += 4;

    return { bytesRead: ptr, result: new Button(style, tag, text, onClick) };
  }

  public override writeTo(writer: NanoBufWriter, offset: number = 0): number {
    let bytesWritten = 20;

    writer.writeTypeId(320412644, offset);

    const styleData = this.style.bytes();
    writer.appendBytes(styleData);
    writer.writeFieldSize(0, styleData.byteLength, offset);
    bytesWritten += styleData.byteLength;

    if (this.tag) {
      writer.appendInt32(this.tag);
      writer.writeFieldSize(1, 4, offset);
      bytesWritten += 4;
    } else {
      writer.writeFieldSize(1, -1, offset);
    }

    const textByteLength = writer.appendString(this.text);
    writer.writeFieldSize(2, textByteLength, offset);
    bytesWritten += textByteLength;

    writer.appendInt32(this.onClick);
    writer.writeFieldSize(3, 4, offset);
    bytesWritten += 4;

    return bytesWritten;
  }

  public override bytes(): Uint8Array {
    const writer = new NanoBufWriter(20);
    this.writeTo(writer);
    return writer.bytes;
  }
}

export { Button };
