// AUTOMATICALLY GENERATED BY NANOPACK. DO NOT MODIFY BY HAND.

import { NanoBufWriter } from "nanopack";
import {
  RpcServer,
  RpcClient,
  RpcMessageType,
  type RpcServerChannel,
} from "nanopack/rpc";

import { Widget } from "./widget/widget.np.js";
import { makeWidget } from "./widget/make-widget.np.js";
import type { NanoPackMessage } from "nanopack";
import { makeNanoPackMessage } from "./message-factory.np.js";

interface INativeLayerService {
  createWindow(
    title: string,
    description: string,
    width: number,
    height: number,
    tag: string,
  ): void;
  createWidget(widget: Widget, windowTag: string): void;
  updateWidget(tag: number, widget: Widget, args: NanoPackMessage): void;
}

class NativeLayerServiceServer extends RpcServer {
  constructor(
    channel: RpcServerChannel,
    private impl: INativeLayerService,
  ) {
    super(channel);
    this.on("create_window", (reader, offset, msgId) => {
      let ptr = offset;
      const titleByteLength = reader.readInt32(ptr);
      ptr += 4;
      const title = reader.readString(ptr, titleByteLength);
      ptr += titleByteLength;
      const descriptionByteLength = reader.readInt32(ptr);
      ptr += 4;
      const description = reader.readString(ptr, descriptionByteLength);
      ptr += descriptionByteLength;
      const width = reader.readInt32(ptr);
      ptr += 4;
      const height = reader.readInt32(ptr);
      ptr += 4;
      const tagByteLength = reader.readInt32(ptr);
      ptr += 4;
      const tag = reader.readString(ptr, tagByteLength);
      ptr += tagByteLength;

      this.impl.createWindow(title, description, width, height, tag);
      const writer = new NanoBufWriter(6);
      writer.appendUint8(RpcMessageType.RESPONSE);
      writer.appendUint32(msgId);
      writer.appendUint8(0);

      return writer;
    });
    this.on("create_widget", (reader, offset, msgId) => {
      let ptr = offset;
      const maybeWidget = makeWidget(reader, ptr);
      if (!maybeWidget) {
        return null;
      }
      const widget = maybeWidget.result;
      ptr += maybeWidget.bytesRead;
      const windowTagByteLength = reader.readInt32(ptr);
      ptr += 4;
      const windowTag = reader.readString(ptr, windowTagByteLength);
      ptr += windowTagByteLength;

      this.impl.createWidget(widget, windowTag);
      const writer = new NanoBufWriter(6);
      writer.appendUint8(RpcMessageType.RESPONSE);
      writer.appendUint32(msgId);
      writer.appendUint8(0);

      return writer;
    });
    this.on("update_widget", (reader, offset, msgId) => {
      let ptr = offset;
      const tag = reader.readUint32(ptr);
      ptr += 4;
      const maybeWidget = makeWidget(reader, ptr);
      if (!maybeWidget) {
        return null;
      }
      const widget = maybeWidget.result;
      ptr += maybeWidget.bytesRead;
      const maybeArgs = makeNanoPackMessage(reader, ptr);
      if (!maybeArgs) {
        return null;
      }
      const args = maybeArgs.result;
      ptr += maybeArgs.bytesRead;

      this.impl.updateWidget(tag, widget, args);
      const writer = new NanoBufWriter(6);
      writer.appendUint8(RpcMessageType.RESPONSE);
      writer.appendUint32(msgId);
      writer.appendUint8(0);

      return writer;
    });
  }
}

class NativeLayerServiceClient extends RpcClient {
  async createWindow(
    title: string,
    description: string,
    width: number,
    height: number,
    tag: string,
  ): Promise<void> {
    const writer = new NanoBufWriter(9 + 13);
    const msgId = this.newMessageId();
    writer.appendUint8(RpcMessageType.REQUEST);
    writer.appendUint32(msgId);
    writer.appendStringAndSize("create_window");
    const titleByteLength = writer.appendStringAndSize(title);
    const descriptionByteLength = writer.appendStringAndSize(description);
    writer.appendInt32(width);
    writer.appendInt32(height);
    const tagByteLength = writer.appendStringAndSize(tag);

    const reader = await this.sendRequestData(msgId, writer.bytes);
    let ptr = 5;
    const errFlag = reader.readUint8(ptr++);
    if (errFlag) {
      throw new Error("error");
    }
  }
  async createWidget(widget: Widget, windowTag: string): Promise<void> {
    const writer = new NanoBufWriter(9 + 13);
    const msgId = this.newMessageId();
    writer.appendUint8(RpcMessageType.REQUEST);
    writer.appendUint32(msgId);
    writer.appendStringAndSize("create_widget");
    const widgetWriteOffset = writer.currentSize;
    writer.reserveHeader(widget.headerSize);
    const widgetByteSize = widget.writeTo(writer, widgetWriteOffset);
    const windowTagByteLength = writer.appendStringAndSize(windowTag);

    const reader = await this.sendRequestData(msgId, writer.bytes);
    let ptr = 5;
    const errFlag = reader.readUint8(ptr++);
    if (errFlag) {
      throw new Error("error");
    }
  }
  async updateWidget(
    tag: number,
    widget: Widget,
    args: NanoPackMessage,
  ): Promise<void> {
    const writer = new NanoBufWriter(9 + 13);
    const msgId = this.newMessageId();
    writer.appendUint8(RpcMessageType.REQUEST);
    writer.appendUint32(msgId);
    writer.appendStringAndSize("update_widget");
    writer.appendUint32(tag);
    const widgetWriteOffset = writer.currentSize;
    writer.reserveHeader(widget.headerSize);
    const widgetByteSize = widget.writeTo(writer, widgetWriteOffset);
    const argsWriteOffset = writer.currentSize;
    writer.reserveHeader(args.headerSize);
    const argsByteSize = args.writeTo(writer, argsWriteOffset);

    const reader = await this.sendRequestData(msgId, writer.bytes);
    let ptr = 5;
    const errFlag = reader.readUint8(ptr++);
    if (errFlag) {
      throw new Error("error");
    }
  }
}

export { NativeLayerServiceServer, NativeLayerServiceClient };
export type { INativeLayerService };
